[package]
name = "ygo_destiny"
version = "0.1.0"
edition = "2021"
license = "GPLv3 only"

[dependencies.ygod_core]
path = "ygod_core"

[dependencies.ygod_gtk]
path = "ygod_gtk"

[dependencies.adw]
features = ["v1_2"]
package = "libadwaita"
version = "0.2"

[dependencies.gtk]
package = "gtk4"
version = "0.5"

[build-dependencies]
glib-build-tools = "0.16"
