[package]
name = "ygo_destiny"
version = "0.1.0"
edition = "2021"
license = "GPLv3 only"

[dependencies.adw]
features = ["v1_2"]
package = "libadwaita"
version = "0.2"

[dependencies.gtk]
package = "gtk4"
version = "0.5"

[dependencies]
bincode = { version = "2.0.0-rc.2", features = ["serde"] }
chrono = "0.4"
directories = "4.0"
once_cell = "1.15.0"
rand = "0.8.5"
regex = "1.6.0"
reqwest = { version = "0.11.12", features = ["blocking", "json"] }
scraper = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies.meml]
git = "https://github.com/myuujiku/meml"
rev = "fd7f52641b2198b1ff2076fd130b875e2e54f9f5"

[build-dependencies]
glib-build-tools = "0.16"
