[package]
name = "ygo_destiny"
version = "0.1.0"
edition = "2021"
license = "GPLv3 only"

[dependencies.relm4]
package = "relm4"
version = "0.5.0-rc.1"
features = ["libadwaita"]

[dependencies.ygod_core]
path = "ygod_core"

[dependencies]
chrono = "0.4"
once_cell = "1.17"
relm4-components = "0.5.0-rc.1"
relm4-macros = "0.5.0-rc.1"
rust-i18n = "1.1"
tracker = "0.2"

[package.metadata.i18n]
load-path = "locales"
available-locales = [
    "en-GB",
    "en-US",
    "de-DE",
    "jp",
]