[package]
name = "ygo_destiny"
version = "0.1.0"
edition = "2021"
license = "GPLv3 only"

[dependencies.adw]
package = "libadwaita"
version = "0.2"
features = ["v1_2"]

[dependencies.relm4]
package = "relm4"
version = "0.5.0"
features = ["libadwaita"]

[dependencies.ygod_core]
git = "https://github.com/myuujiku/ygod_core"
rev = "df38d959ff5ad7e1124213536eb3915e8e87926d"

[dependencies]
chrono = "0.4"
once_cell = "1.17"
relm4-components = "0.5.0"
relm4-macros = "0.5.0"
rust-i18n = "1.1"
tracker = "0.2"

[build-dependencies]
glib-build-tools = "0.17"

[package.metadata.i18n]
load-path = "locales"
available-locales = [
    "de-DE",
    "en-GB",
    "fr-FR",
    "it-IT",
    "pt-PT",
]
